---
title: "Untitled"
author: "Jaehwan Lim"
date: "February 6, 2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
library(readxl)
theme_set(theme_light())

party_cc <- read_excel("~/Downloads/CC+Data+Jobcoded+18CC+-+ACC (5).xlsx") %>% 
  rename(purgede = pursede, march = lmarch)
```

```{r}
## tidying the data 
party_cc_tidied <- party_cc %>% 
  gather(job, value, starts_with("job")) 

party_cc_tidied %>% 
  filter(value %in% c(8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19)) %>% 
  count(value) %>% 
  ggplot(aes(value, n)) +
  geom_line(size = 0.8) + 
  geom_line(data = alternate, aes(value, n), linetype = "dashed") +
  expand_limits(y = 0) +
  scale_x_continuous(breaks = seq(8, 19, 1), 
                     labels = c("8(1956)", "9(1969)", "10(1973)", "11(1977)", "12(1982)", "13(1987)", "14(1992)", "15(1997)", "16(2002)", "17(2007)", "18(2012)", "19(2017)")) + 
  labs(title = "Number of CC full and alternate members", 
       x = "Party congress", 
       y = "")

## what about alternate members?
alternate <- party_cc_tidied %>% filter(value %in% c(8.1, 9.1, 10.1, 11.1, 12.1, 13.1, 14.1, 15.1, 16.1, 17.1, 18.1, 19.1)) %>% count(value)

party_cc_tidied %>% filter(name1 == "Huang Huahua")
```

```{r}
## subsetting by national congress
party_cc_7 <- party_cc_tidied %>% filter(value == 7.0)
party_cc_8 <- party_cc_tidied %>% filter(value == 8.0) 
party_cc_9 <- party_cc_tidied %>% filter(value == 9.0)
party_cc_10 <- party_cc_tidied %>% filter(value == 10.0)
party_cc_11 <- party_cc_tidied %>% filter(value == 11.0)
party_cc_12 <- party_cc_tidied %>% filter(value == 12.0)
party_cc_13 <- party_cc_tidied %>% filter(value == 13.0)
party_cc_14 <- party_cc_tidied %>% filter(value == 14.0)
party_cc_15 <- party_cc_tidied %>% filter(value == 15.0)
party_cc_16 <- party_cc_tidied %>% filter(value == 16.0)
party_cc_17 <- party_cc_tidied %>% filter(value == 17.0)
party_cc_18 <- party_cc_tidied %>% filter(value == 18.0)

party_cc_8new <- party_cc_8 %>% anti_join(party_cc_7, by = "name")
party_cc_9new <- party_cc_9 %>% anti_join(party_cc_8, by = "name")
party_cc_10new <- party_cc_10 %>% anti_join(party_cc_9, by = "name")
party_cc_11new <- party_cc_11 %>% anti_join(party_cc_10, by = "name")
party_cc_12new <- party_cc_12 %>% anti_join(party_cc_11, by = "name")
party_cc_13new <- party_cc_13 %>% anti_join(party_cc_12, by = "name")
party_cc_14new <- party_cc_14 %>% anti_join(party_cc_13, by = "name")
party_cc_15new <- party_cc_15 %>% anti_join(party_cc_14, by = "name")
party_cc_16new <- party_cc_16 %>% anti_join(party_cc_15, by = "name")
party_cc_17new <- party_cc_17 %>% anti_join(party_cc_16, by = "name")
party_cc_18new <- party_cc_18 %>% anti_join(party_cc_17, by = "name")

party_cc_9leave <- party_cc_8 %>% anti_join(party_cc_9, by = "name") 
party_cc_10leave <- party_cc_9 %>% anti_join(party_cc_10, by = "name") 
party_cc_11leave <- party_cc_10 %>% anti_join(party_cc_11, by = "name")
party_cc_12leave <- party_cc_11 %>% anti_join(party_cc_12, by = "name")
party_cc_13leave <- party_cc_12 %>% anti_join(party_cc_13, by = "name")
party_cc_14leave <- party_cc_13 %>% anti_join(party_cc_14, by = "name")
party_cc_15leave <- party_cc_14 %>% anti_join(party_cc_15, by = "name")
party_cc_16leave <- party_cc_15 %>% anti_join(party_cc_16, by = "name")
party_cc_17leave <- party_cc_16 %>% anti_join(party_cc_17, by = "name")
party_cc_18leave <- party_cc_17 %>% anti_join(party_cc_18, by = "name")

```

## On average, how many steps a cadre should go through before one becomes a member of CC?


```{r}
all_8new <- party_cc_tidied %>% semi_join(party_cc_8new) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(congress = ifelse(value == 8, value, 8)) %>% 
  mutate(congress_age = 1956 - birth)

all_9new <- party_cc_tidied %>% semi_join(party_cc_9new) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(congress = ifelse(value == 9, value, 9)) %>% 
  mutate(congress_age = 1969 - birth)

all_10new <- party_cc_tidied %>% semi_join(party_cc_10new) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(congress = ifelse(value == 10, value, 10)) %>% 
  mutate(congress_age = 1973 - birth)

all_11new <- party_cc_tidied %>% semi_join(party_cc_11new) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(congress = ifelse(value == 11, value, 11)) %>% 
  mutate(congress_age = 1977 - birth)

all_12new <- party_cc_tidied %>% semi_join(party_cc_12new) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(congress = ifelse(value == 12, value, 12)) %>% 
  mutate(congress_age = 1982 - birth)

all_13new <- party_cc_tidied %>% semi_join(party_cc_13new) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(congress = ifelse(value == 13, value, 13)) %>% 
  mutate(congress_age = 1987 - birth)

all_14new <- party_cc_tidied %>% semi_join(party_cc_14new) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(congress = ifelse(value == 14, value, 14)) %>% 
  mutate(congress_age = 1992 - birth)

all_15new <- party_cc_tidied %>% semi_join(party_cc_15new) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(congress = ifelse(value == 15, value, 15)) %>% 
  mutate(congress_age = 1997 - birth)

all_16new <- party_cc_tidied %>% semi_join(party_cc_16new) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(congress = ifelse(value == 16, value, 16)) %>% 
  mutate(congress_age = 2002 - birth)

all_17new <- party_cc_tidied %>% semi_join(party_cc_17new) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(congress = ifelse(value == 17, value, 17)) %>% 
  mutate(congress_age = 2007 - birth)

all_18new <- party_cc_tidied %>% semi_join(party_cc_18new) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(congress = ifelse(value == 18, value, 18)) %>% 
  mutate(congress_age = 2012 - birth)

## binding all congresses and creating a dataset
all_newcomers <- bind_rows(all_8new, all_9new, all_10new, all_11new, all_12new, all_13new, all_14new, all_15new, all_16new, all_17new, all_18new)

## Plotting a lineplot on the average of promotions before entering the CC
all_newcomers %>% group_by(congress) %>% 
  summarize(mean_jobs = mean(job)) %>% 
  ggplot(aes(congress, mean_jobs)) +
  geom_line() +
  geom_point() +
  expand_limits(y = 4) +
  scale_x_continuous(breaks = seq(8, 18, 1), 
                     labels = c("8(1956)", "9(1969)", "10(1973)", "11(1977)", "12(1982)", "13(1987)", "14(1992)", "15(1997)", "16(2002)", "17(2007)", "18(2012)"))

## Plotting a boxplot on the average of promotions 
all_newcomers %>% group_by(congress) %>%
  ggplot(aes(congress, job)) +
  geom_boxplot(aes(group = congress)) + 
  scale_x_continuous(breaks = seq(8, 18, 1), 
                     labels = c("8(1956)", "9(1969)", "10(1973)", "11(1977)", "12(1982)", "13(1987)", "14(1992)", "15(1997)", "16(2002)", "17(2007)", "18(2012)")) +
  labs(title = "Figure 4. Career-path of the newcomers to the CC", 
       x = "", 
       y = "Number of jobs")

all_newcomers %>% group_by(congress) %>% 
  summarize(median_age = median(congress_age)) %>% 
  ggplot(aes(congress, median_age)) +
  geom_line() +
  geom_point() +
  expand_limits(y = 40) +
  scale_x_continuous(breaks = seq(8, 18, 1), 
                     labels = c("8(1956)", "9(1969)", "10(1973)", "11(1977)", "12(1982)", "13(1987)", "14(1992)", "15(1997)", "16(2002)", "17(2007)", "18(2012)"))

all_newcomers %>% group_by(congress) %>% 
  ggplot(aes(congress, congress_age)) +
  geom_boxplot(aes(group = congress)) + 
  scale_x_continuous(breaks = seq(8, 18, 1), 
                     labels = c("8(1956)", "9(1969)", "10(1973)", "11(1977)", "12(1982)", "13(1987)", "14(1992)", "15(1997)", "16(2002)", "17(2007)", "18(2012)")) +
<<<<<<< HEAD
  labs(title = "Figure 1. Distribution of entry age at CC in post-1949 party congresses", 
=======
  labs(title = "Figure 3. Distribution of entry age at CC in post-1949 party congresses", 
>>>>>>> f24ebb7dd95e385f2f57226c568388d0f698e1bc
       x = "", 
       y = "Age", 
       caption = "Source: Original dataset built on Shih et al 2012") + 
  coord_flip()

all_newcomers_sel <- all_newcomers %>% select(name, congress, congress_age) %>% rename("entry_cong" = congress, "entry_age" = congress_age)

all_newcomers_sel <- all_newcomers %>% select(name, congress, congress_age) %>% rename("entry_cong" = congress, "entry_age" = congress_age)

```
## Age of Retirees 
```{r}
all_9retiree <- party_cc_tidied %>% semi_join(party_cc_9leave) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(retire_cong = ifelse(value == 8, 9, 9)) %>% 
  mutate(retire_age = 1969 - birth)

all_10retiree <- party_cc_tidied %>% semi_join(party_cc_10leave) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(retire_cong = ifelse(value == 9, 10, 10)) %>% 
  mutate(retire_age = 1973 - birth)

all_11retiree <- party_cc_tidied %>% semi_join(party_cc_11leave) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(retire_cong = ifelse(value == 10, 11, 11)) %>% 
  mutate(retire_age = 1977 - birth)

all_12retiree <- party_cc_tidied %>% semi_join(party_cc_12leave) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(retire_cong = ifelse(value == 11, 12, 12)) %>% 
  mutate(retire_age = 1982 - birth)

all_13retiree <- party_cc_tidied %>% semi_join(party_cc_13leave) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(retire_cong = ifelse(value == 12, 13, 13)) %>% 
  mutate(retire_age = 1987 - birth)

all_14retiree <- party_cc_tidied %>% semi_join(party_cc_14leave) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(retire_cong = ifelse(value == 13, 14, 14)) %>% 
  mutate(retire_age = 1992 - birth)

all_15retiree <- party_cc_tidied %>% semi_join(party_cc_15leave) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(retire_cong = ifelse(value == 14, 15, 15)) %>% 
  mutate(retire_age = 1997 - birth)

all_16retiree <- party_cc_tidied %>% semi_join(party_cc_16leave) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(retire_cong = ifelse(value == 15, 16, 16)) %>% 
  mutate(retire_age = 2002 - birth)

all_15retiree %>% arrange(desc(retire_age))

all_17retiree <- party_cc_tidied %>% semi_join(party_cc_17leave) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(retire_cong = ifelse(value == 16, 17, 17)) %>% 
  mutate(retire_age = 2007 - birth)

all_18retiree <- party_cc_tidied %>% semi_join(party_cc_18leave) %>% 
  mutate(job = as.numeric(str_remove(job, "job"))) %>% 
  mutate(retire_cong = ifelse(value == 17, 18, 18)) %>% 
  mutate(retire_age = 2012 - birth)

## binding all congresses and creating a dataset
all_retirees <- bind_rows(all_9retiree, all_10retiree, all_11retiree, all_12retiree, all_13retiree, all_14retiree, all_15retiree, all_16retiree, all_17retiree, all_18retiree)

all_retirees %>% select(name, retire_cong, retire_age) %>% 
  filter(retire_cong == 15, retire_age > 70)

## Plotting
all_retirees %>%  
  ggplot(aes(retire_cong, retire_age)) +
  geom_boxplot(aes(group = retire_cong)) + 
  scale_x_continuous(breaks = seq(9, 18, 1), 
                     labels = c("9(1969)", "10(1973)", "11(1977)", "12(1982)", "13(1987)", "14(1992)", "15(1997)", "16(2002)", "17(2007)", "18(2012)")) +
  scale_y_continuous(breaks = seq(30, 100, 10), 
                     labels = seq(30, 100, 10)) +
  labs(title = "Figure 2. Distribution of retirement age at CC in post-1949 party congresses", 
       x = "", 
       y = "Age", 
       caption = "Source: Original dataset built on Shih et al 2012") + 
  coord_flip() +
  labs(title = "Figure 4. Distribution of retirement age at CC in post-1949 party congresses", 
       x = "", 
       y = "Age", 
       caption = "Source: Original dataset built on Shih et al 2012")

all_retirees_sel <- all_retirees %>% select(name, retire_cong, retire_age) 

party_cc_tidied %>% 
  left_join(all_newcomers_sel, by = "name") %>% 
  left_join(all_retirees_sel, by = "name") %>% 
  gather(cong, age, entry_cong:retire_age) 


```

### What determines the likelihood of the alternates getting the full membership?

```{r}
alternate_member <- party_cc_tidied %>% filter(value %in% c(8.1, 9.1, 10.1, 11.1, 12.1, 13.1, 14.1, 15.1, 16.1, 17.1, 18.1)) 

alternate_member %>% left_join(party_cc_tidied, by = "name") %>% 
  mutate(full_cc = ifelse(value.y %in% c(9, 10, 11, 12, 13, 14, 15, 16, 17, 18), 1, 0)) %>% 
  View()


```

